# src/config.py
# Словарь расширений файлов → имена папок-назначений
EXTENSION_MAP = {
    ".jpg": "Pictures",
    ".jpeg": "Pictures",
    ".png": "Pictures",
    ".gif": "Pictures",
    ".jfif": "Pictures",
    ".webp": "Pictures",
    ".HEIC": "Pictures",
    ".mp4": "Videos",
    ".mkv": "Videos",
    ".webm": "Videos",
    ".mp3": "Audio",
    ".wav": "Audio",
    ".pdf": "Documents",
    ".cfg": "Documents",
    ".md": "Documents",
    ".odt": "Documents",
    ".docx": "Documents",
    ".xlsx": "Documents",
    ".pptx": "Documents",
    ".txt": "Documents",
    ".zip": "Archives",
    ".rar": "Archives",
    ".7z": "Archives",
    ".py": "Code",
    ".java": "Code",
    ".c": "Code",
    ".cpp": "Code",
    ".html": "Code",
    ".css": "Code",
    ".js": "Code",
    ".json": "Code",
    ".jar": "Code"
}
